# Generated by Django 3.2.9 on 2021-11-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('comment', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=300)),
            ],
        ),
    ]
